name: SurvivalGames
version: 0.6.1-B
main: org.mcsg.survivalgames.SurvivalGames
## Authors ##
authors: [Double0Negative, ThunderGemios10]
description: Fully Automated Hunger Games Plugin!
depend: [WorldEdit]

commands:
    survivalgames:
        description: Survival Games Command
        usage: /sg <command> <args>
        aliases: [sg, hungergames, hg]

